// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: droids.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcNETService.Generated {

  /// <summary>Holder for reflection information generated from droids.proto</summary>
  public static partial class DroidsReflection {

    #region Descriptor
    /// <summary>File descriptor for droids.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DroidsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxkcm9pZHMucHJvdG8iDwoNRHJvaWRzUmVxdWVzdCIlCgtEcm9pZHNSZXBs",
            "eRIWCgZkcm9pZHMYASADKAsyBi5Ecm9pZCKsAQoFRHJvaWQSEAoIYXJtYW1l",
            "bnQYASADKAkSDQoFY2xhc3MYAiABKAkSEQoJZXF1aXBtZW50GAMgAygJEg4K",
            "BmhlaWdodBgEIAEoBRIUCgxtYW51ZmFjdHVyZXIYBSABKAkSDQoFbW9kZWwY",
            "BiABKAkSFQoNcGxhdGluZ19jb2xvchgHIAMoCRINCgVwcmljZRgIIAEoBRIU",
            "CgxzZW5zb3JfY29sb3IYCSADKAkyNgoMRHJvaWRTZXJ2aWNlEiYKBkdldEFs",
            "bBIOLkRyb2lkc1JlcXVlc3QaDC5Ecm9pZHNSZXBseUIbqgIYR3JwY05FVFNl",
            "cnZpY2UuR2VuZXJhdGVkYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcNETService.Generated.DroidsRequest), global::GrpcNETService.Generated.DroidsRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcNETService.Generated.DroidsReply), global::GrpcNETService.Generated.DroidsReply.Parser, new[]{ "Droids" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcNETService.Generated.Droid), global::GrpcNETService.Generated.Droid.Parser, new[]{ "Armament", "Class", "Equipment", "Height", "Manufacturer", "Model", "PlatingColor", "Price", "SensorColor" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DroidsRequest : pb::IMessage<DroidsRequest> {
    private static readonly pb::MessageParser<DroidsRequest> _parser = new pb::MessageParser<DroidsRequest>(() => new DroidsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DroidsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcNETService.Generated.DroidsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DroidsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DroidsRequest(DroidsRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DroidsRequest Clone() {
      return new DroidsRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DroidsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DroidsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DroidsRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class DroidsReply : pb::IMessage<DroidsReply> {
    private static readonly pb::MessageParser<DroidsReply> _parser = new pb::MessageParser<DroidsReply>(() => new DroidsReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DroidsReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcNETService.Generated.DroidsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DroidsReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DroidsReply(DroidsReply other) : this() {
      droids_ = other.droids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DroidsReply Clone() {
      return new DroidsReply(this);
    }

    /// <summary>Field number for the "droids" field.</summary>
    public const int DroidsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::GrpcNETService.Generated.Droid> _repeated_droids_codec
        = pb::FieldCodec.ForMessage(10, global::GrpcNETService.Generated.Droid.Parser);
    private readonly pbc::RepeatedField<global::GrpcNETService.Generated.Droid> droids_ = new pbc::RepeatedField<global::GrpcNETService.Generated.Droid>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GrpcNETService.Generated.Droid> Droids {
      get { return droids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DroidsReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DroidsReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!droids_.Equals(other.droids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= droids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      droids_.WriteTo(output, _repeated_droids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += droids_.CalculateSize(_repeated_droids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DroidsReply other) {
      if (other == null) {
        return;
      }
      droids_.Add(other.droids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            droids_.AddEntriesFrom(input, _repeated_droids_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Droid : pb::IMessage<Droid> {
    private static readonly pb::MessageParser<Droid> _parser = new pb::MessageParser<Droid>(() => new Droid());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Droid> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcNETService.Generated.DroidsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Droid() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Droid(Droid other) : this() {
      armament_ = other.armament_.Clone();
      class_ = other.class_;
      equipment_ = other.equipment_.Clone();
      height_ = other.height_;
      manufacturer_ = other.manufacturer_;
      model_ = other.model_;
      platingColor_ = other.platingColor_.Clone();
      price_ = other.price_;
      sensorColor_ = other.sensorColor_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Droid Clone() {
      return new Droid(this);
    }

    /// <summary>Field number for the "armament" field.</summary>
    public const int ArmamentFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_armament_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> armament_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Armament {
      get { return armament_; }
    }

    /// <summary>Field number for the "class" field.</summary>
    public const int ClassFieldNumber = 2;
    private string class_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Class {
      get { return class_; }
      set {
        class_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "equipment" field.</summary>
    public const int EquipmentFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_equipment_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> equipment_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Equipment {
      get { return equipment_; }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 4;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "manufacturer" field.</summary>
    public const int ManufacturerFieldNumber = 5;
    private string manufacturer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Manufacturer {
      get { return manufacturer_; }
      set {
        manufacturer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 6;
    private string model_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plating_color" field.</summary>
    public const int PlatingColorFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_platingColor_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> platingColor_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> PlatingColor {
      get { return platingColor_; }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 8;
    private int price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "sensor_color" field.</summary>
    public const int SensorColorFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_sensorColor_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> sensorColor_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> SensorColor {
      get { return sensorColor_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Droid);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Droid other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!armament_.Equals(other.armament_)) return false;
      if (Class != other.Class) return false;
      if(!equipment_.Equals(other.equipment_)) return false;
      if (Height != other.Height) return false;
      if (Manufacturer != other.Manufacturer) return false;
      if (Model != other.Model) return false;
      if(!platingColor_.Equals(other.platingColor_)) return false;
      if (Price != other.Price) return false;
      if(!sensorColor_.Equals(other.sensorColor_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= armament_.GetHashCode();
      if (Class.Length != 0) hash ^= Class.GetHashCode();
      hash ^= equipment_.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (Manufacturer.Length != 0) hash ^= Manufacturer.GetHashCode();
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      hash ^= platingColor_.GetHashCode();
      if (Price != 0) hash ^= Price.GetHashCode();
      hash ^= sensorColor_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      armament_.WriteTo(output, _repeated_armament_codec);
      if (Class.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Class);
      }
      equipment_.WriteTo(output, _repeated_equipment_codec);
      if (Height != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Height);
      }
      if (Manufacturer.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Manufacturer);
      }
      if (Model.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Model);
      }
      platingColor_.WriteTo(output, _repeated_platingColor_codec);
      if (Price != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Price);
      }
      sensorColor_.WriteTo(output, _repeated_sensorColor_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += armament_.CalculateSize(_repeated_armament_codec);
      if (Class.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Class);
      }
      size += equipment_.CalculateSize(_repeated_equipment_codec);
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (Manufacturer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Manufacturer);
      }
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      size += platingColor_.CalculateSize(_repeated_platingColor_codec);
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      size += sensorColor_.CalculateSize(_repeated_sensorColor_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Droid other) {
      if (other == null) {
        return;
      }
      armament_.Add(other.armament_);
      if (other.Class.Length != 0) {
        Class = other.Class;
      }
      equipment_.Add(other.equipment_);
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.Manufacturer.Length != 0) {
        Manufacturer = other.Manufacturer;
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      platingColor_.Add(other.platingColor_);
      if (other.Price != 0) {
        Price = other.Price;
      }
      sensorColor_.Add(other.sensorColor_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            armament_.AddEntriesFrom(input, _repeated_armament_codec);
            break;
          }
          case 18: {
            Class = input.ReadString();
            break;
          }
          case 26: {
            equipment_.AddEntriesFrom(input, _repeated_equipment_codec);
            break;
          }
          case 32: {
            Height = input.ReadInt32();
            break;
          }
          case 42: {
            Manufacturer = input.ReadString();
            break;
          }
          case 50: {
            Model = input.ReadString();
            break;
          }
          case 58: {
            platingColor_.AddEntriesFrom(input, _repeated_platingColor_codec);
            break;
          }
          case 64: {
            Price = input.ReadInt32();
            break;
          }
          case 74: {
            sensorColor_.AddEntriesFrom(input, _repeated_sensorColor_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
