// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: droids.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcNETService.Generated {
  public static partial class DroidService
  {
    static readonly string __ServiceName = "DroidService";

    static readonly grpc::Marshaller<global::GrpcNETService.Generated.DroidsRequest> __Marshaller_DroidsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcNETService.Generated.DroidsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcNETService.Generated.DroidsReply> __Marshaller_DroidsReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcNETService.Generated.DroidsReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcNETService.Generated.DroidsRequest, global::GrpcNETService.Generated.DroidsReply> __Method_GetAll = new grpc::Method<global::GrpcNETService.Generated.DroidsRequest, global::GrpcNETService.Generated.DroidsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAll",
        __Marshaller_DroidsRequest,
        __Marshaller_DroidsReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcNETService.Generated.DroidsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DroidService</summary>
    [grpc::BindServiceMethod(typeof(DroidService), "BindService")]
    public abstract partial class DroidServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcNETService.Generated.DroidsReply> GetAll(global::GrpcNETService.Generated.DroidsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DroidServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAll, serviceImpl.GetAll).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DroidServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAll, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcNETService.Generated.DroidsRequest, global::GrpcNETService.Generated.DroidsReply>(serviceImpl.GetAll));
    }

  }
}
#endregion
